### ISSUE TITLE
CAD files?

### ISSUE THREAD

**Issue by gabrielgrant** [DavidWenzler/reAM250#3]
The BoM document references a lot of small, individual part CAD files, and [this article](https://3dprintingindustry.com/news/build-your-own-metal-3d-printer-with-the-new-open-source-ream250-project-234965/) shows a screenshot of a whole-system CAD file:

  
![image](https://github.com/user-attachments/assets/fabe1d1e-3082-417e-92ec-5826738ebc74)

Apparently this image was sourced from Autodesk, but a screen grab of a small section of this model also appears on the 5th page of the released paper: https://www.sciencedirect.com/science/article/pii/S221282712400475X

Are these CAD files available somewhere?

**Comment by SquishyBoiFrog** [comment]
Yeah they are here: https://davidwenzler.github.io/reAM250/docs/getting-started/

Along with some other helpful information.

**Comment by gabrielgrant** [comment]
Ah, hadn't seen this site! Would be great to add this as the repo's official link in the about section

eg:

![image](https://github.com/user-attachments/assets/18e85a50-6bf5-40e2-af24-5f315223a8d4)

**Comment by DavidWenzler** [comment]
Thanks for the feedback. I included the link in the README file on the official site.
