### ISSUE TITLE
Build Material selection (Main enclosure)

### ISSUE THREAD

**Issue by SquishyBoiFrog** [DavidWenzler/reAM250#4]
The current question I have is the seals for the enclosure. I don't thing this enclosure needs to be air tight  which opens up a lot of option. Does it need to be high temp resistant? 
![image](https://github.com/user-attachments/assets/eaadb294-b204-47ca-b6bd-c08eac47fa5a)

-This following image is of the main enclosure frame that has 6 seals of different sizes, all the blue items are seals.

**Comment by DavidWenzler** [comment]
We ended up using this material (LIQUI MOLY 6185) to seal the chamber, as it is necessary to maintain the shielding gas atmosphere
