### ISSUE TITLE
B&R licensing for contributors?

### ISSUE THREAD

**Issue by npeacock** [DavidWenzler/reAM250#5]
I was checking out the getting started steps to run the simulator.  This use of the automation studio from B&R requires a license.  I thought I could just use the free license but reading the terms.

"Commercial use takes place if the automation system configured in Automation Studio is sold or made available to a third party with or without the goal of realizing profit, inspected or modified."

It seems like agreeing to this would limit sharing back anything I change.  The TUM code in the PLC folder is all linked up with the B&R libraries.  In general this seems like it would limit the ability of this to grow as an open source project, unless someone has a different interpretation of the licensing.

**Comment by DavidWenzler** [comment]
We designed our script to be transferable to other PLC systems by implementing classes using an implementation pattern, effectively separating the B&R environment from our scripts. This allows the code to be easily transferable if necessary.

**Comment by DavidWenzler** [comment]
To state on the license. Our project was developed for research and education. As long as you are using the software for research and education you can obtain a free educational license of Automation Studio. If you are using the software outside of research and education, you have to buy a license from B&R.
